name: e2e - Ubuntu

on:
  workflow_dispatch:

jobs:
  migrate_ubuntu_pg14:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Run migration on Ubuntu for PostgreSQL 14
        run: npx @neondatabase/migrate-pg --accept-all true --source ${{ secrets.SOURCE_PG14 }} --destination ${{ secrets.DESTINATION_PG14 }}

  migrate_ubuntu_pg15:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Run migration on Ubuntu for PostgreSQL 15
        run: npx @neondatabase/migrate-pg --accept-all true --source ${{ secrets.SOURCE_PG15 }} --destination ${{ secrets.DESTINATION_PG15 }}

  migrate_ubuntu_pg16:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Run migration on Ubuntu for PostgreSQL 16
        run: npx @neondatabase/migrate-pg --accept-all true --source ${{ secrets.SOURCE_PG16 }} --destination ${{ secrets.DESTINATION_PG16 }}
